### ISSUE TITLE
Love to participate

### ISSUE THREAD

**Issue by rubelux** [ryhope/pando#1]
Hi Guys, 

I have been thinking about a decentralized GIT with a reward layer and using Aragon for governance for a year or so and suddenly I came across this project yesterday after checking Aragon Nest.

Having a UI interface build with Electron similar to Aragon's will be critical for the UX and I could help on that but I guess that's quite down the line for you now, anyway I would love to help with anything you need.

Ruben

**Comment by osarrouy** [comment]
Hi Ruben !

Thanks a lot for your interest.

We are definitely thinking about building a dedicated UI interface to handle pando repositories!

That's not our top priority for now since we are still working on developing the protocol layer and CLI tool but we are open to start some UI research about that. If you have some skills in front-end dev and UI / UX design that could make it.

Maybe you would need some more info on how the protocol works though ? Or are you Solidity fluent ? :)

**Comment by rubelux** [comment]
Hi @osarrouy 

I could help with UX design, UI, and front-end development with Reactjs and Nodejs and Electron if this stack is what you guys have in mind for the frontend.

About Solidity, I know it but I'd not say I am fluent so I'd need a bit of help to understand how the protocol works.

Thanks :)

**Comment by osarrouy** [comment]
Hey @rubelux,

Sorry for the delay. We were quite busy releasing the version alpha version. You can now `npm install -g @pando/cli' to test the cli tool :)

The best would be for us to chat a little we our designer. Do you have a matrix id so that we can invite you on our chat room ?

Otherwise we're gonna open a gitter chat.

Let us know !
